using System;

namespace Ferraris
{
    [Serializable] public class GeoPoint { public double lon, lat; }
    [Serializable] public class MapPoint { public float x, z; public MapPoint(float x, float z) { this.x=x; this.z=z; } }
    [Serializable] public class AreaData
    {
        public string name, crs;
        public double lat, lon, originE, originN;
        public float size, heightBase, heightRange;
        public int heightResolution, geoResolution;
        public float[] heights;
        public GeoPoint[] geoGrid;

        // +X east, +Z north, metres from EPSG:31370 projected origin.
        // The grid is generated by PyProj (EPSG:31370 -> EPSG:4326, always_xy).
        // It stores south-to-north rows, unlike a north-up image's pixel rows.
        // Bilinear interpolation over 62.5m cells is <1cm from PROJ in tests.
        public GeoPoint UnityToGeoCoordinate(double x, double z)
        {
            Cell(x,z,geoResolution,out int i,out int j,out double u,out double v);
            GeoPoint a=geoGrid[j*geoResolution+i], b=geoGrid[j*geoResolution+i+1];
            GeoPoint c=geoGrid[(j+1)*geoResolution+i],d=geoGrid[(j+1)*geoResolution+i+1];
            return new GeoPoint { lon=Mix(a.lon,b.lon,c.lon,d.lon,u,v),lat=Mix(a.lat,b.lat,c.lat,d.lat,u,v) };
        }
        public MapPoint GeoCoordinateToUnity(double latitude, double longitude)
        {
            // Newton inversion of the same smooth lookup, preserving both axes.
            double x=0,z=0;
            for(int k=0;k<6;k++)
            {
                double sx=x>0?-.1:.1,sz=z>0?-.1:.1;
                GeoPoint p=UnityToGeoCoordinate(x,z),e=UnityToGeoCoordinate(x+sx,z),n=UnityToGeoCoordinate(x,z+sz);
                double a=(e.lon-p.lon)/sx,b=(n.lon-p.lon)/sz,c=(e.lat-p.lat)/sx,d=(n.lat-p.lat)/sz;
                double dx=longitude-p.lon,dz=latitude-p.lat,det=a*d-b*c;
                if(Math.Abs(det)<1e-16) throw new ArgumentOutOfRangeException("Coordinate outside generated area");
                x+=(dx*d-b*dz)/det; z+=(a*dz-dx*c)/det;
            }
            if(Math.Abs(x)>size/2+.02 || Math.Abs(z)>size/2+.02) throw new ArgumentOutOfRangeException("Coordinate outside generated area");
            return new MapPoint((float)x,(float)z);
        }
        public float Height(float x,float z)
        {
            x=Math.Clamp(x,-size/2,size/2);z=Math.Clamp(z,-size/2,size/2);
            Cell(x,z,heightResolution,out int i,out int j,out double u,out double v);
            return (float)Mix(heights[j*heightResolution+i],heights[j*heightResolution+i+1],heights[(j+1)*heightResolution+i],heights[(j+1)*heightResolution+i+1],u,v)-heightBase;
        }
        public MapPoint MapUVToUnity(float u,float v) => new MapPoint((u-.5f)*size,(v-.5f)*size);
        void Cell(double x,double z,int n,out int i,out int j,out double u,out double v)
        {
            // Extrapolate during Newton's edge correction; clamping the value
            // makes the derivative zero. Inversion checks final area bounds.
            u=(x/size+.5)*(n-1);v=(z/size+.5)*(n-1);
            i=Math.Clamp((int)u,0,n-2);j=Math.Clamp((int)v,0,n-2);u-=i;v-=j;
        }
        static double Mix(double a,double b,double c,double d,double u,double v) => (a*(1-u)+b*u)*(1-v)+(c*(1-u)+d*u)*v;
    }
    [Serializable] public class Road { public MapPoint[] points; public float width; }
    [Serializable] public class Building
    {
        public float x,z,width,depth,yaw; public string id,kind,legend;
        public MapPoint[] footprint,roof;
        public bool Contains(float px,float pz)
        {
            if(footprint==null||footprint.Length<3)
            {
                double angle=yaw*Math.PI/180,dx=px-x,dz=pz-z;
                double lx=Math.Cos(angle)*dx-Math.Sin(angle)*dz,lz=Math.Sin(angle)*dx+Math.Cos(angle)*dz;
                return Math.Abs(lx)<=width/2&&Math.Abs(lz)<=depth/2;
            }
            bool inside=false;
            for(int i=0,j=footprint.Length-1;i<footprint.Length;j=i++)
            {
                var a=footprint[i];var b=footprint[j];
                if((a.z>pz)!=(b.z>pz)&&px<(b.x-a.x)*(pz-a.z)/(b.z-a.z)+a.x)inside=!inside;
            }
            return inside;
        }
    }
    [Serializable] public class Patch { public MapPoint[] points; public string kind; }
    [Serializable] public class Tree { public float x,z,scale; }
    [Serializable] public class WorldData { public Road[] roads; public Building[] buildings; public Patch[] patches; public Tree[] trees; }
}
